version: "3.0"

volumes:

  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mysql/data

services:

  mysql:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: gpn
      MYSQL_PASSWORD: gpnpa$$Word
      MYSQL_DATABASE: gpn
    restart: unless-stopped

  app:
    build: ../GPN
    ports:
      - 5000:5000
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ../GPN:/usr/src/app
      - /etc/localtime:/etc/localtime
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - MYSQL_USER=gpn
      - MYSQL_HOST=172.17.0.1
      - MYSQL_PASSWORD=gpnpa$$Word
      - MYSQL_DATABASE=gpn
      - REDIS_URL=redis://redis:6379/0
    restart: always
    depends_on:
      - mysql
      - redis

  celery_app:
    build: ../GPN
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    volumes:
      - ../GPN:/usr/src/app
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - MYSQL_USER=gpn
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=gpnpa$$Word
      - MYSQL_DATABASE=gpn
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - app
      - redis

  redis:
    image: redis:7
    restart: unless-stopped