version: "1.0"

volumes:

  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./mysql/data

services:

  mysql:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: gpn
      MYSQL_PASSWORD: gpnpa$$Word
      MYSQL_DATABASE: gpn

  gpn:
    build:
      context: ../GPN
      dockerfile: ./Dockerfile
    image: gpn/gpn:0.1
    links:
      - mysql:mysql
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=gpn
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=gpnpa$$Word
      - MYSQL_DATABASE=gpn
    depends_on:
      - mysql
